---
title: "bug_productivity"
author: "Lydia Bleifuss"
date: "5/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo=TRUE, message=FALSE}
library(DeclareDesign)
library(knitr)
library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(kableExtra)
```

```{r bug declare pop, echo=TRUE, message=F, eval=TRUE, cache=TRUE}

#declaring population of bug grids

#set.seed(228)
#population <- declare_population(
  #pollinator_grids = add_level(N=3250000, 
    # bug_count=runif(n=N, min=0, max=30))
#)
#pop <- population()
#plot <- ggplot(pop, aes(x=bug_count)) + 
 # geom_histogram(color="black", fill="white")
#plot
```

```{r bug sample, echo=TRUE, message=F, eval=TRUE}

#Drawing a sample

#sam <- sample(1:3250000,40)
#plot2 <- ggplot(pop, aes(x=bug_count)) + 
 # geom_histogram(color="black", fill="white") +
  #geom_histogram(data=pop[sam,], fill = "black")

#plot2
```

## Conceptual practice: stratification

- Describe a monitoring situation where you might want to use stratified sampling
    + What are the strata?
    + How would you allocate sampling effort across the strata?

## DeclareDesign()

```{r declare-pop}
set.seed(228)
population <- declare_population(
  bug_grids = add_level(N=3250000, 
     good_habitat=draw_binary(N=N, prob = 0.3),
     bugs=correlate(given = good_habitat, rho = 0.5,
                         draw_count, mean = 15)
))

my_estimand <- declare_estimands(mean(bugs),
                                 label = "Ybar")
```

## DeclareDesign()

```{r declare-report}
#reporting <- declare_assignment(area=good_habitat,
                  #assignment_variable = "R",
                  #area_prob=c(0.3,0.7))

sampling <- declare_sampling(strata=good_habitat,
                             strata_n=c(20,20))

```

## DeclareDesign()

```{r declare-estimator}

strata_weighted_mean <- function(data){
  data.frame(  
  estimator_label = "strata_w_mean",
  estimand_label = "Ybar",
  n = nrow(data),
  stringsAsFactors = FALSE,
  
  estimate = data %>% 
    group_by(good_habitat) %>% 
    summarise(mean=mean(bugs)) %>%
    mutate(prop=c(0.5,0.5)) %>%
    mutate(sub.mean=mean*prop) %>% pull(sub.mean) %>% 
    sum())
} #just use this function, custom

```

## DeclareDesign()

```{r diagnosis, cache=TRUE}

answer <- declare_estimator(
  handler = tidy_estimator(strata_weighted_mean),
  estimand = my_estimand)

design <- population + my_estimand +
          sampling + answer
diagnosis <- diagnose_design(design, sims = 500)

diagnosis$diagnosands_df[,c(4,5,12,14)] %>%
  kable()

```