---
title: "groundwater_levels"
author: "Lydia Bleifuss"
date: "5/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Groundwater Levels:
Medow area is 300 acres or approximately 13,000,000 sq ft
40 samples of 10x10 ft grids
Sampled area covers about 20% of meadow area

```{r load, echo=TRUE, message=FALSE}
library(DeclareDesign)
library(knitr)
library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(kableExtra)
```

```{r groundwater_pop, echo=TRUE, message=F, eval=TRUE, cache=TRUE}
#declaring population of groundwater grids 
set.seed(228)
population <- declare_population(
  gw_grids = add_level(N=130000, 
     gw_count=runif(n=N, min=0, max=24))
)

pop <- population()
plot <- ggplot(pop, aes(x=gw_count)) + 
  geom_histogram(color="black", fill="white")

plot
```


```{r willow-sample, echo=TRUE, message=F, eval=TRUE}
#Drawing a sample
sam <- sample(1:130000,40)
plot2 <- ggplot(pop, aes(x=gw_count)) + 
  geom_histogram(color="black", fill="white") +
  geom_histogram(data=pop[sam,], fill = "black")

plot2

```


```{r mean-compare}
## Realizations vs. expectations
mean(pop$gw_count)
mean(pop[sam,"gw_count"])
```

```{r declare-pop}
population <- declare_population(
  gw_grids = add_level(N=130000, 
     main=draw_count(mean=8),
     inundated=correlate(given = main, rho = 0.5,
                         draw_count)
))
```


```{r declare-report}
#reporting <- declare_assignment(blocks=main,
                  #assignment_variable = "R",
                  #block_prob=c(0.2,0.5))

sampling <- declare_sampling(n=40)

my_estimand <- declare_estimands(mean(inundated),
                                 label = "Ybar")

answer <- declare_estimator(inundated ~ 1,
                            model = lm_robust,
                            label = "est.")

```

## DeclareDesign()

```{r diagnosis}
design <- population + sampling + 
  my_estimand + answer

diagnosis <- diagnose_design(design)

diagnosis$diagnosands_df[,c(5,11,13,15)] %>%
  kable()

```


