---
title: "willow_thickets"
author: "Lydia Bleifuss"
date: "5/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Willow Thicket:
Riparian buffer is 8.6 acres
40 samples of 10x10 ft 
Coversabout 10% of riparian buffer

```{r load, echo=TRUE, message=FALSE}
library(DeclareDesign)
library(knitr)
library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
library(kableExtra)
```

```{r willow pop, echo=TRUE, message=F, eval=TRUE, cache=TRUE}
#declaring population of willows 
set.seed(228)
population <- declare_population(
  willows = add_level(N=3744,
                      main=draw_count(N=N, prob = 1),
     willow_count=runif(n=N, min=0, max=50))
)

population

population <- population()
plot <- ggplot(population, aes(x=willow_count)) + 
  geom_histogram(color="black", fill="white")
plot
```

```{r declare-pop}
population <- declare_population(
  households = add_level(N=500, 
     main=draw_count(N=N, prob = 0.5),
     satisfied=correlate(given = main, rho = 0.5,
                         draw_binary, prob = 0.5)
))
```


```{r willow-sample, echo=TRUE, message=F, eval=TRUE}
#Drawing a sample
sam <- sample(1:3744,40)
plot2 <- ggplot(pop, aes(x=willow_count)) + 
  geom_histogram(color="black", fill="white") +
  geom_histogram(data=pop[sam,], fill = "black")

```


```{r mean-compare}
## Realizations vs. expectations
mean(population$willow_count)
#[1] 24.94215
willow_mean <- mean(population$willow_count)

mean(population[sam,"willow_count"])
#[1] 25.07221
```


```{r sam-dist, cache=TRUE}
#Sampling distribution:the distribution of sample values with a repeated draw of a given sampling frame.

#Sampling frame: this procedure describing the sample to be drawn.

sims <- 1000
store <- rep(NA, sims)
for (i in 1:sims){
  store[i] <- mean(pop[sample(1:3744,40),"willow_count"])
}


mean(store) #expected sample mean

## [1] 24.81467

sd(store) #standard error (standard deviation of the sampling distribution)

## [1] 2.158915

sd(pop[sam, "willow_count"]) #standard deviation of sample

# [1] 14.00425
```


```{r plot-sam, echo=FALSE, message=FALSE, fig.height=3.5, warning=FALSE}

##Sampling distribution
sam.dist <- ggplot(data.frame(store), aes(x=store)) + 
  geom_histogram(color="black", fill="white") +
  xlab("Mean value of sample") + xlim(c(0,35)) +
  annotate("text",-Inf,Inf,label="n=3744", hjust = 0, vjust = 1)
sam.dist
```

```{r sam-summary}
mean(store) #expected sample mean
# [1] 24.81467
sd(store) #standard error
# [1] 2.158915
```


```{r sd-vs-se}
## Standard deviation vs. standard error

sd(pop[sam,"willow_count"]) #standard deviation of sample
# [1] 14.00425

sd(store) #standard error of sample
#[1] 2.158915

```


```{r declare-report}

## DeclareDesign

sampling <- declare_sampling(n=40)


my_estimand <- declare_estimands(mean(willow_mean))


answer <- declare_estimator(willow_count ~ 1,
                            model = lm_robust,
                            label = "est.") #simple mean, works without stratification (take out R==1)
answer

```



```{r diagnosis}
## DeclareDesign
design <- population + sampling + my_estimand + answer
diagnosis <- diagnose_design(design)

diagnosis$diagnosands_df[,c(40)] %>%
  kable()
```
